# Generated by Django 2.1.7 on 2019-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('availibility_status', models.BooleanField(default=True)),
                ('car_registration_number', models.IntegerField()),
                ('car_color', models.CharField(max_length=200)),
            ],
        ),
    ]
