# Generated by Django 2.1.7 on 2019-03-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carparking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslots',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='parkingslots',
            name='car_registration_number',
        ),
    ]
